### Week 1 - Picking Best Single Feature (Income - Spending)

In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report, roc_auc_score

In [106]:
# Reading data
acct_df = pd.read_parquet("data/q2-ucsd-acctDF.pqt")
cons_df = pd.read_parquet("data/q2-ucsd-consDF.pqt")
txn_df = pd.read_parquet("data/q2-ucsd-trxnDF.pqt")
cat_map_df = pd.read_csv("data/q2-ucsd-cat-map.csv")

### Visualize each dataframe

In [107]:
acct_df

      prism_consumer_id prism_account_id account_type balance_date   balance
0                  3023                0      SAVINGS   2021-08-31     90.57
1                  3023                1     CHECKING   2021-08-31    225.95
2                  4416                2      SAVINGS   2022-03-31  15157.17
3                  4416                3     CHECKING   2022-03-31     66.42
4                  4227                4     CHECKING   2021-07-31   7042.90
...                 ...              ...          ...          ...       ...
24461             11500            24461     CHECKING   2022-03-27    732.75
24462             11615            24462      SAVINGS   2022-03-30      5.00
24463             11615            24463     CHECKING   2022-03-30   1956.46
24464             12210            24464     CHECKING   2022-03-28   2701.51
24465             11615            24465     CHECKING   2022-03-30   7967.45

[24466 rows x 5 columns]

In [56]:
train_df = cons_df[:12000]
train_df

      prism_consumer_id evaluation_date  credit_score  DQ_TARGET
0                     0      2021-09-01         726.0        0.0
1                     1      2021-07-01         626.0        0.0
2                     2      2021-05-01         680.0        0.0
3                     3      2021-03-01         734.0        0.0
4                     4      2021-10-01         676.0        0.0
...                 ...             ...           ...        ...
11995             11995      2022-03-19         623.0        0.0
11996             11996      2022-03-18         617.0        0.0
11997             11997      2022-02-25         646.0        0.0
11998             11998      2022-02-09         773.0        0.0
11999             11999      2021-12-12         646.0        0.0

[12000 rows x 4 columns]

In [4]:
len(cons_df['prism_consumer_id'].unique())

15000

In [5]:
txn_df

,prism_consumer_id,prism_transaction_id,category,amount,credit_or_debit,posted_date
0,3023,0,4,0.05,CREDIT,2021-04-16
1,3023,1,12,481.56,CREDIT,2021-04-30
2,3023,2,4,0.05,CREDIT,2021-05-16
3,3023,3,4,0.07,CREDIT,2021-06-16
4,3023,4,4,0.06,CREDIT,2021-07-16
...,...,...,...,...,...,...
6407316,10533,6405304,31,4.96,DEBIT,2022-03-11
6407317,10533,6405305,12,63.48,DEBIT,2022-03-30
6407318,10533,6405306,12,53.99,DEBIT,2022-03-30
6407319,10533,6405307,12,175.98,DEBIT,2022-03-31
6407320,10533,6405308,14,16.04,DEBIT,2022-03-31

In [6]:
cat_map_df

    category_id               category
0             0          SELF_TRANSFER
1             1      EXTERNAL_TRANSFER
2             2                DEPOSIT
3             3               PAYCHECK
4             4          MISCELLANEOUS
5             5   PAYCHECK_PLACEHOLDER
6             6                 REFUND
7             7      INVESTMENT_INCOME
8             8         OTHER_BENEFITS
9             9  UNEMPLOYMENT_BENEFITS
10           10   SMALL_DOLLAR_ADVANCE
11           11                    TAX
12           12                   LOAN
13           13              INSURANCE
14           14     FOOD_AND_BEVERAGES
15           15          UNCATEGORIZED
16           16    GENERAL_MERCHANDISE
17           17             AUTOMOTIVE
18           18              GROCERIES
19           19               ATM_CASH
20           20          ENTERTAINMENT
21           21                 TRAVEL
22           22     ESSENTIAL_SERVICES
23           23           ACCOUNT_FEES
24           24       HOME_IMPROVEMENT
25           25              OVERDRAFT
26           26    CREDIT_CARD_PAYMENT
27           27     HEALTHCARE_MEDICAL
28           28                   PETS
29           29              EDUCATION
30           30        GIFTS_DONATIONS
31           31        BILLS_UTILITIES
32           32               MORTGAGE
33           33       CHILD_DEPENDENTS
34           34                   RENT
35           35                   BNPL
36           36              AUTO_LOAN
37           37      BANKING_CATCH_ALL
38           38                   DEBT
39           39                FITNESS
40           40          TRANSPORATION
41           41                  LEGAL
42           42    GOVERNMENT_SERVICES
43           43         RISK_CATCH_ALL
44           44                RTO_LTO
45           45             INVESTMENT
46           46               GAMBLING
47           47     CORPORATE_PAYMENTS
48           48          TIME_OR_STUFF
49           49                PENSION

### Data Preprocessing

In [7]:
# Convert Category Mappings to a dictionary

cat_map = dict()

for i in range(cat_map_df.shape[0]):
    cat_map[i] = cat_map_df['category'].iloc[i]

cat_map

{0: 'SELF_TRANSFER',
 1: 'EXTERNAL_TRANSFER',
 2: 'DEPOSIT',
 3: 'PAYCHECK',
 4: 'MISCELLANEOUS',
 5: 'PAYCHECK_PLACEHOLDER',
 6: 'REFUND',
 7: 'INVESTMENT_INCOME',
 8: 'OTHER_BENEFITS',
 9: 'UNEMPLOYMENT_BENEFITS',
 10: 'SMALL_DOLLAR_ADVANCE',
 11: 'TAX',
 12: 'LOAN',
 13: 'INSURANCE',
 14: 'FOOD_AND_BEVERAGES',
 15: 'UNCATEGORIZED',
 16: 'GENERAL_MERCHANDISE',
 17: 'AUTOMOTIVE',
 18: 'GROCERIES',
 19: 'ATM_CASH',
 20: 'ENTERTAINMENT',
 21: 'TRAVEL',
 22: 'ESSENTIAL_SERVICES',
 23: 'ACCOUNT_FEES',
 24: 'HOME_IMPROVEMENT',
 25: 'OVERDRAFT',
 26: 'CREDIT_CARD_PAYMENT',
 27: 'HEALTHCARE_MEDICAL',
 28: 'PETS',
 29: 'EDUCATION',
 30: 'GIFTS_DONATIONS',
 31: 'BILLS_UTILITIES',
 32: 'MORTGAGE',
 33: 'CHILD_DEPENDENTS',
 34: 'RENT',
 35: 'BNPL',
 36: 'AUTO_LOAN',
 37: 'BANKING_CATCH_ALL',
 38: 'DEBT',
 39: 'FITNESS',
 40: 'TRANSPORATION',
 41: 'LEGAL',
 42: 'GOVERNMENT_SERVICES',
 43: 'RISK_CATCH_ALL',
 44: 'RTO_LTO',
 45: 'INVESTMENT',
 46: 'GAMBLING',
 47: 'CORPORATE_PAYMENTS',
 48: 'TIME_OR_STUFF',
 49: 'PENSION'}

In [8]:
# Map all categories into the dataframe

txn_df['category'] = txn_df['category'].apply(lambda x: cat_map[x])

In [9]:
# Divide the transaction dataset into debit and credit

deb_txn = txn_df[txn_df['credit_or_debit'] == "DEBIT"]
cre_txn = txn_df[txn_df['credit_or_debit'] == "CREDIT"]

In [10]:
sum(deb_txn['amount'] < 0)

0

In [11]:
cre_txn[cre_txn['amount'] < 0]['category'].value_counts()

Series([], Name: count, dtype: int64)

In [12]:
cre_txn[cre_txn['amount'] > 0]['category'].value_counts()

category
SELF_TRANSFER            342392
EXTERNAL_TRANSFER        216021
PAYCHECK                 180208
DEPOSIT                  114156
MISCELLANEOUS            112397
REFUND                    60841
INVESTMENT_INCOME         21813
LOAN                      13585
TAX                       10262
UNEMPLOYMENT_BENEFITS      7521
INVESTMENT                 6684
PENSION                    6032
TIME_OR_STUFF              5660
OTHER_BENEFITS             5513
INSURANCE                  1432
GAMBLING                    424
CORPORATE_PAYMENTS           22
Name: count, dtype: int64

In [13]:
txn_df['category'].unique()

array(['MISCELLANEOUS', 'LOAN', 'EXTERNAL_TRANSFER', 'DEPOSIT',
       'SELF_TRANSFER', 'INVESTMENT', 'PAYCHECK', 'REFUND',
       'ENTERTAINMENT', 'FOOD_AND_BEVERAGES', 'GROCERIES', 'FITNESS',
       'GENERAL_MERCHANDISE', 'HEALTHCARE_MEDICAL', 'GAMBLING',
       'GIFTS_DONATIONS', 'CREDIT_CARD_PAYMENT', 'AUTOMOTIVE',
       'HOME_IMPROVEMENT', 'ATM_CASH', 'TRANSPORATION', 'PENSION',
       'INSURANCE', 'TAX', 'ACCOUNT_FEES', 'RENT', 'BILLS_UTILITIES',
       'ESSENTIAL_SERVICES', 'EDUCATION', 'TRAVEL', 'PETS', 'MORTGAGE',
       'BANKING_CATCH_ALL', 'DEBT', 'AUTO_LOAN', 'BNPL',
       'GOVERNMENT_SERVICES', 'CORPORATE_PAYMENTS', 'LEGAL',
       'RISK_CATCH_ALL', 'OTHER_BENEFITS', 'TIME_OR_STUFF',
       'UNEMPLOYMENT_BENEFITS', 'CHILD_DEPENDENTS', 'RTO_LTO',
       'INVESTMENT_INCOME', 'OVERDRAFT'], dtype=object)

### Feature Engineering

To find the best feature, I am trying to aggregate the transaction df on consumer-level and get a feature (net monthly income) that represent "estimated monthly income" - "estimated monthly spending".

In [120]:
# Aggregate transaction amount based on individual consumer and year-month pair

txn_df['year_month'] = pd.to_datetime(txn_df['posted_date']).dt.to_period('M')

txn_aggregated = txn_df.groupby(['prism_consumer_id', 'year_month']).agg(
    monthly_income=('amount', lambda x: x[txn_df.loc[x.index, 'credit_or_debit'] == 'CREDIT'].sum()),
    monthly_spending=('amount', lambda x: x[txn_df.loc[x.index, 'credit_or_debit'] == 'DEBIT'].sum())
).reset_index()

txn_aggregated

      prism_consumer_id year_month  monthly_income  monthly_spending
0                     0    2021-03         2400.69           1999.35
1                     0    2021-04         3210.66           2379.93
2                     0    2021-05          967.00            765.50
3                     0    2021-06         1068.13           3652.37
4                     0    2021-07         2204.83           2276.21
...                 ...        ...             ...               ...
89548              9998    2023-10         5140.21           5124.35
89549              9999    2023-05         7664.45           4488.76
89550              9999    2023-06        12576.78          12813.20
89551              9999    2023-07        10370.51          11658.85
89552              9999    2023-08         1166.08           3136.44

[89553 rows x 4 columns]

In [15]:
txn_aggregated['monthly_net_income'] = txn_aggregated.apply(lambda row: row['monthly_income'] - row['monthly_spending'], axis = 1)
txn_aggregated

,prism_consumer_id,year_month,monthly_income,monthly_spending,monthly_net_income
0,0,2021-03,2400.69,1999.35,401.34
1,0,2021-04,3210.66,2379.93,830.73
2,0,2021-05,967.00,765.50,201.50
3,0,2021-06,1068.13,3652.37,-2584.24
4,0,2021-07,2204.83,2276.21,-71.38
...,...,...,...,...,...
89548,9998,2023-10,5140.21,5124.35,15.86
89549,9999,2023-05,7664.45,4488.76,3175.69
89550,9999,2023-06,12576.78,12813.20,-236.42
89551,9999,2023-07,10370.51,11658.85,-1288.34
89552,9999,2023-08,1166.08,3136.44,-1970.36

In [16]:
txn_avg_monthly = txn_aggregated.groupby('prism_consumer_id').agg(
    average_nmi=('monthly_net_income', 'mean')
).reset_index()

txn_avg_monthly

      prism_consumer_id  average_nmi
0                     0   -74.512857
1                     1   257.918571
2                    10  -170.005714
3                   100  -750.961667
4                  1000    62.582857
...                 ...          ...
14487              9995   -30.387500
14488              9996     2.285000
14489              9997   125.797500
14490              9998  -277.700000
14491              9999   -79.857500

[14492 rows x 2 columns]

In [ ]:
def zscoring_normalize(df, column):
    # Calculate the mean and standard deviation of the entire balance column
    mean = df[column].mean()
    std = df[column].std()

    # Z-score normalization
    df[column + '_z_score'] = (df[column] - mean) / std

In [76]:
txn_avg_monthly

zscoring_normalize(txn_avg_monthly, 'average_nmi')

      prism_consumer_id  average_nmi  average_nmi_z_score
0                     0   -74.512857            -0.065380
1                     1   257.918571            -0.029751
2                    10  -170.005714            -0.075614
3                   100  -750.961667            -0.137879
4                  1000    62.582857            -0.050687
...                 ...          ...                  ...
14487              9995   -30.387500            -0.060651
14488              9996     2.285000            -0.057149
14489              9997   125.797500            -0.043912
14490              9998  -277.700000            -0.087157
14491              9999   -79.857500            -0.065953

[14492 rows x 3 columns]

In [17]:
txn_cons = set(txn_avg_monthly['prism_consumer_id'].unique())
cons_cons = set(cons_df['prism_consumer_id'].unique())

len(cons_cons - txn_cons)

508

In [18]:
cons_cons - txn_cons

{'10234',
 '11008',
 '11504',
 '11655',
 '11918',
 '12101',
 '12780',
 '12932',
 '13479',
 '13607',
 '13750',
 '14056',
 '14163',
 '14206',
 '14435',
 '14749',
 '14916',
 '5003',
 '5007',
 '5024',
 '5036',
 '5044',
 '5082',
 '5084',
 '5102',
 '5107',
 '5109',
 '5115',
 '5125',
 '5129',
 '5130',
 '5149',
 '5166',
 '5177',
 '5179',
 '5186',
 '5200',
 '5202',
 '5206',
 '5228',
 '5247',
 '5272',
 '5283',
 '5284',
 '5295',
 '5298',
 '5301',
 '5302',
 '5308',
 '5311',
 '5315',
 '5319',
 '5332',
 '5335',
 '5351',
 '5366',
 '5381',
 '5388',
 '5403',
 '5423',
 '5437',
 '5451',
 '5469',
 '5496',
 '5506',
 '5513',
 '5524',
 '5528',
 '5543',
 '5558',
 '5588',
 '5600',
 '5608',
 '5612',
 '5614',
 '5634',
 '5649',
 '5660',
 '5670',
 '5671',
 '5690',
 '5697',
 '5714',
 '5716',
 '5722',
 '5732',
 '5755',
 '5758',
 '5773',
 '5788',
 '5814',
 '5829',
 '5830',
 '5844',
 '5845',
 '5866',
 '5868',
 '5878',
 '5890',
 '5902',
 '5913',
 '5947',
 '5962',
 '5966',
 '5968',
 '6033',
 '6044',
 '6046',
 '6052',
 '6057',
 '6064',
 '6071',
 '6083',
 '6119',
 '6128',
 '6161',
 '6166',
 '6200',
 '6214',
 '6242',
 '6248',
 '6268',
 '6269',
 '6277',
 '6285',
 '6289',
 '6314',
 '6329',
 '6339',
 '6342',
 '6350',
 '6351',
 '6366',
 '6367',
 '6382',
 '6383',
 '6385',
 '6390',
 '6406',
 '6410',
 '6412',
 '6423',
 '6444',
 '6451',
 '6460',
 '6464',
 '6468',
 '6481',
 '6508',
 '6524',
 '6528',
 '6531',
 '6540',
 '6549',
 '6552',
 '6556',
 '6574',
 '6583',
 '6603',
 '6604',
 '6652',
 '6679',
 '6681',
 '6699',
 '6712',
 '6746',
 '6750',
 '6766',
 '6789',
 '6811',
 '6823',
 '6830',
 '6833',
 '6834',
 '6835',
 '6849',
 '6857',
 '6865',
 '6872',
 '6876',
 '6878',
 '6882',
 '6888',
 '6898',
 '6912',
 '6913',
 '6929',
 '6941',
 '6948',
 '6961',
 '6969',
 '6978',
 '6982',
 '6987',
 '6995',
 '7005',
 '7019',
 '7021',
 '7022',
 '7024',
 '7030',
 '7047',
 '7051',
 '7056',
 '7059',
 '7060',
 '7071',
 '7101',
 '7117',
 '7121',
 '7122',
 '7123',
 '7135',
 '7148',
 '7152',
 '7156',
 '7157',
 '7187',
 '7193',
 '7204',
 '7211',
 '7226',
 '7228',
 '7229',
 '7235',
 '7236',
 '7257',
 '7259',
 '7263',
 '7265',
 '7268',
 '7277',
 '7283',
 '7285',
 '7302',
 '7331',
 '7334',
 '7353',
 '7354',
 '7367',
 '7386',
 '7390',
 '7394',
 '7397',
 '7405',
 '7407',
 '7409',
 '7413',
 '7419',
 '7425',
 '7435',
 '7445',
 '7453',
 '7456',
 '7463',
 '7491',
 '7493',
 '7509',
 '7510',
 '7520',
 '7531',
 '7538',
 '7547',
 '7570',
 '7577',
 '7581',
 '7596',
 '7600',
 '7606',
 '7611',
 '7620',
 '7622',
 '7634',
 '7639',
 '7643',
 '7651',
 '7660',
 '7668',
 '7691',
 '7707',
 '7733',
 '7737',
 '7756',
 '7763',
 '7767',
 '7772',
 '7838',
 '7843',
 '7896',
 '7900',
 '7905',
 '7906',
 '7908',
 '7927',
 '7928',
 '7948',
 '7950',
 '7960',
 '7971',
 '7974',
 '7976',
 '7983',
 '7986',
 '8000',
 '8001',
 '8020',
 '8024',
 '8025',
 '8035',
 '8049',
 '8053',
 '8058',
 '8068',
 '8070',
 '8073',
 '8083',
 '8084',
 '8085',
 '8086',
 '8092',
 '8105',
 '8110',
 '8112',
 '8116',
 '8123',
 '8125',
 '8162',
 '8195',
 '8202',
 '8208',
 '8220',
 '8226',
 '8251',
 '8256',
 '8260',
 '8264',
 '8300',
 '8326',
 '8334',
 '8337',
 '8350',
 '8370',
 '8459',
 '8465',
 '8471',
 '8478',
 '8497',
 '8505',
 '8507',
 '8545',
 '8556',
 '8580',
 '8588',
 '8599',
 '8611',
 '8621',
 '8630',
 '8635',
 '8644',
 '8652',
 '8662',
 '8664',
 '8700',
 '8711',
 '8715',
 '8725',
 '8726',
 '8729',
 '8737',
 '8740',
 '8745',
 '8764',
 '8766',
 '8770',
 '8786',
 '8787',
 '8797',
 '8808',
 '8820',
 '8821',
 '8824',
 '8829',
 '8830',
 '8835',
 '8840',
 '8858',
 '8861',
 '8863',
 '8864',
 '8867',
 '8871',
 '8872',
 '8873',
 '8877',
 '8878',
 '8885',
 '8888',
 '8903',
 '8914',
 '8923',
 '8933',
 '8936',
 '8959',
 '8982',
 '8992',
 '9015',
 '9019',
 '9020',
 '9031',
 '9048',
 '9059',
 '9063',
 '9100',
 '9107',
 '9110',
 '9117',
 '9119',
 '9140',
 '9153',
 '9168',
 '9172',
 '9174',
 '9178',
 '9202',
 '9219',
 '9230',
 '9242',
 '9244',
 '9245',
 '9247',
 '9268',
 '9269',
 '9286',
 '9292',
 '9300',
 '9311',
 '9313',
 '9320',
 '9329',
 '9358',
 '9361',
 '9376',
 '9381',
 '9405',
 '9437',
 '9442',
 '9443',
 '9451',
 '9454',
 '9458',
 '9464',
 '9470',
 '9482',
 '9515',
 '9524',
 '9527',
 '9530',
 '9535',
 '9558',
 '9560',
 '9561',
 '9589',
 '9591',
 '9596',
 '9598',
 '9605',
 '9614',
 '9620',
 '9621',
 '9629',
 '9638',
 '9640',
 '9641',
 '9654',
 '9662',
 '9671',
 '9678',
 '9681',
 '9683',
 '9696',
 '9703',
 '9719',
 '9722',
 '9738',
 '9740',
 '9741',
 '9758',
 '9781',
 '9817',
 '9824',
 '9832',
 '9848',
 '9859',
 '9861',
 '9864',
 '9885',
 '9898',
 '9914',
 '9930',
 '9933',
 '9945',
 '9948',
 '9951',
 '9953',
 '9963',
 '9968',
 '9977',
 '9992'}

In [19]:
cons_txn_merged = cons_df.merge(txn_avg_monthly, on='prism_consumer_id', how='left')

In [57]:
train_df = train_df[['prism_consumer_id', 'DQ_TARGET']]

In [122]:
#txn_df['year_month'] = pd.to_datetime(txn_df['posted_date']).dt.to_period('M')
acct_df['year_month'] = pd.to_datetime(acct_df['balance_date']).dt.to_period('M')
acct_df

,prism_consumer_id,prism_account_id,account_type,balance_date,balance,year_month
0,3023,0,SAVINGS,2021-08-31,90.57,2021-08
1,3023,1,CHECKING,2021-08-31,225.95,2021-08
2,4416,2,SAVINGS,2022-03-31,15157.17,2022-03
3,4416,3,CHECKING,2022-03-31,66.42,2022-03
4,4227,4,CHECKING,2021-07-31,7042.90,2021-07
...,...,...,...,...,...,...
24461,11500,24461,CHECKING,2022-03-27,732.75,2022-03
24462,11615,24462,SAVINGS,2022-03-30,5.00,2022-03
24463,11615,24463,CHECKING,2022-03-30,1956.46,2022-03
24464,12210,24464,CHECKING,2022-03-28,2701.51,2022-03
24465,11615,24465,CHECKING,2022-03-30,7967.45,2022-03

In [123]:
txn_df

,prism_consumer_id,prism_transaction_id,category,amount,credit_or_debit,posted_date,year_month
0,3023,0,4,0.05,CREDIT,2021-04-16,2021-04
1,3023,1,12,481.56,CREDIT,2021-04-30,2021-04
2,3023,2,4,0.05,CREDIT,2021-05-16,2021-05
3,3023,3,4,0.07,CREDIT,2021-06-16,2021-06
4,3023,4,4,0.06,CREDIT,2021-07-16,2021-07
...,...,...,...,...,...,...,...
6407316,10533,6405304,31,4.96,DEBIT,2022-03-11,2022-03
6407317,10533,6405305,12,63.48,DEBIT,2022-03-30,2022-03
6407318,10533,6405306,12,53.99,DEBIT,2022-03-30,2022-03
6407319,10533,6405307,12,175.98,DEBIT,2022-03-31,2022-03
6407320,10533,6405308,14,16.04,DEBIT,2022-03-31,2022-03

# Model Training

In [89]:
# Define a function to train Logistic Regression on a dataframe
def train_logistic_regression(df):
    """
    Train a logistic regression model using all columns (except the first) to predict the first column.

    Args:
        df (pd.DataFrame): Input dataframe where the first column (excluding index) is the target variable.

    Returns:
        None: Prints model evaluation metrics.
    """
    # Ensure the dataframe has at least two columns
    if df.shape[1] < 2:
        raise ValueError("The dataframe must have at least two columns.")
    
    temp = train_df.merge(df, on='prism_consumer_id', how='left')
    temp = temp.dropna()
    temp = temp.drop(columns=['prism_consumer_id'])

    # Separate features (X) and target (y)
    y = temp['DQ_TARGET']
    X = temp.drop(columns=['DQ_TARGET'])

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

    # Train Logistic Regression
    clf = LogisticRegression(random_state=0, max_iter=1000, class_weight="balanced")
    clf.fit(X_train, y_train)

    # Predict probabilities and classes
    y_pred = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred, average='weighted')
    auc = roc_auc_score(y_test, y_proba)

    print("Accuracy:", accuracy)
    print("F1 Score:", f1)
    print("AUC-ROC Score:", auc)
    print("Classification Report:\n", classification_report(y_test, y_pred))

In [85]:
# Normalized Average Net Monthly Inflow

train_logistic_regression(txn_avg_monthly[['prism_consumer_id', 'average_nmi_z_score']])

Accuracy: 0.9171523730224813
F1 Score: 0.8779169729170678
AUC-ROC Score: 0.5656485453445526
Classification Report:
               precision    recall  f1-score   support

         0.0       0.92      1.00      0.96      2204
         1.0       0.00      0.00      0.00       198

    accuracy                           0.92      2402
   macro avg       0.46      0.50      0.48      2402
weighted avg       0.84      0.92      0.88      2402

In [92]:
# Normalized balance
acct_balance_df = acct_df.groupby("prism_consumer_id").agg(balance_sum = ('balance', 'sum')).reset_index()

zscoring_normalize(acct_balance_df, 'balance_sum')

train_logistic_regression(acct_balance_df[['prism_consumer_id', 'balance_sum_z_score']])

Accuracy: 0.3793254489706526
F1 Score: 0.46760211409791264
AUC-ROC Score: 0.7389294932217358
Classification Report:
               precision    recall  f1-score   support

         0.0       0.98      0.33      0.49      2089
         1.0       0.11      0.92      0.20       194

    accuracy                           0.38      2283
   macro avg       0.55      0.63      0.35      2283
weighted avg       0.91      0.38      0.47      2283

In [118]:
acct_df[acct_df["prism_consumer_id"] == '11615']

      prism_consumer_id prism_account_id account_type balance_date  balance
24462             11615            24462      SAVINGS   2022-03-30     5.00
24463             11615            24463     CHECKING   2022-03-30  1956.46
24465             11615            24465     CHECKING   2022-03-30  7967.45

In [115]:
acct_df["prism_consumer_id"][0]

'3023'

In [117]:
acct_df["prism_consumer_id"]

0         3023
1         3023
2         4416
3         4416
4         4227
         ...
24461    11500
24462    11615
24463    11615
24464    12210
24465    11615
Name: prism_consumer_id, Length: 24466, dtype: object